cc_test(
    name = "visit_ast_lib_test",
    srcs = ["visit_ast_lib_test.cc"],
    deps = [
        "//src:visit_ast_lib",
        "//src/visitors:cast_visitor",
        "//src/visitors:goto_visitor",
        "//src/visitors:nobreak_visitor",
        "@com_google_googletest//:gtest",
    ],
)